# Generated by Django 4.2.30 on 2026-05-18 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='visitor_key',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['listing', 'visitor_key', 'viewed_at'], name='listings_vi_listing_64c1c6_idx'),
        ),
    ]
