# Generated by Django 4.2.30 on 2026-05-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_viewhistory_visitor_key_alter_viewhistory_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['region', 'city', 'district'],
            },
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('region', 'city', 'district'), name='unique_address_region_city_district'),
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.address'),
        ),
    ]
